import { jsPDF } from "jspdf";
import { BRAND } from "./brand";

export type PayslipPdfData = {
  id: string;
  period_year: number;
  period_month: number;
  base_salary: number | string;
  present_days: number | string;
  absent_days: number | string;
  paid_leave_days: number | string;
  unpaid_leave_days: number | string;
  working_days: number | string;
  overtime_hours: number | string;
  deductions: number | string;
  net_pay: number | string;
  generated_at?: string;
};

export type PayslipContext = {
  employeeName: string;
  employeeEmail?: string | null;
  companyName?: string | null;
};

const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"];

const inr = (n: number | string) => "Rs. " + Number(n || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 });

export function downloadPayslipPdf(payslip: PayslipPdfData, ctx: PayslipContext) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 48;

  // Header
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, W, 80, "F");
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold").setFontSize(22).text(BRAND.name, 40, 48);
  doc.setFont("helvetica", "normal").setFontSize(11).text("Payslip", 40, 66);
  doc.setFontSize(11).text(`${MONTHS[payslip.period_month - 1]} ${payslip.period_year}`, W - 40, 48, { align: "right" });

  doc.setTextColor(20);
  y = 110;

  // Company / employee
  doc.setFont("helvetica", "bold").setFontSize(12).text(ctx.companyName ?? "Company", 40, y);
  doc.setFont("helvetica", "normal").setFontSize(10);
  y += 24;
  doc.text(`Employee: ${ctx.employeeName}`, 40, y);
  if (ctx.employeeEmail) { y += 14; doc.text(`Email: ${ctx.employeeEmail}`, 40, y); }
  y += 14;
  doc.text(`Generated: ${new Date(payslip.generated_at ?? Date.now()).toLocaleDateString("en-IN")}`, 40, y);

  // Attendance summary box
  y += 24;
  doc.setDrawColor(220); doc.setFillColor(248, 250, 252);
  doc.roundedRect(40, y, W - 80, 90, 6, 6, "FD");
  doc.setFont("helvetica", "bold").setFontSize(11).text("Attendance summary", 56, y + 22);
  doc.setFont("helvetica", "normal").setFontSize(10);
  const col = (label: string, val: string, x: number, ry: number) => {
    doc.setTextColor(120); doc.text(label, x, ry);
    doc.setTextColor(20); doc.setFont("helvetica", "bold").text(val, x, ry + 16);
    doc.setFont("helvetica", "normal");
  };
  const cy = y + 50;
  col("Working days", String(payslip.working_days), 56, cy);
  col("Present", String(payslip.present_days), 176, cy);
  col("Paid leave", String(payslip.paid_leave_days), 286, cy);
  col("Unpaid leave", String(payslip.unpaid_leave_days), 396, cy);
  col("Absent", String(payslip.absent_days), 506, cy);

  // Earnings / deductions
  y += 110;
  doc.setFont("helvetica", "bold").setFontSize(11).text("Earnings & deductions", 40, y);
  y += 12;
  doc.setDrawColor(220); doc.line(40, y, W - 40, y);
  y += 18;
  const row = (label: string, value: string, bold = false) => {
    doc.setFont("helvetica", bold ? "bold" : "normal").setFontSize(10).setTextColor(20);
    doc.text(label, 56, y);
    doc.text(value, W - 56, y, { align: "right" });
    y += 20;
  };
  row("Base salary", inr(payslip.base_salary));
  row("Overtime hours", String(payslip.overtime_hours));
  row("Deductions (unpaid leave / absences)", "- " + inr(payslip.deductions));
  doc.setDrawColor(220); doc.line(40, y - 6, W - 40, y - 6);
  y += 6;
  doc.setFillColor(238, 242, 255); doc.rect(40, y - 14, W - 80, 36, "F");
  row("Net pay", inr(payslip.net_pay), true);

  // Footer
  doc.setFontSize(9).setTextColor(140);
  doc.text(`Generated by ${BRAND.name} · This is a system-generated payslip and does not require a signature.`, W / 2, 800, { align: "center" });

  const fname = `Payslip_${ctx.employeeName.replace(/\s+/g, "_")}_${payslip.period_year}-${String(payslip.period_month).padStart(2, "0")}.pdf`;
  doc.save(fname);
}
