/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedPinResetsRouteImport } from './routes/_authenticated/pin-resets'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedMySalaryRouteImport } from './routes/_authenticated/my-salary'
import { Route as AuthenticatedMyLeavesRouteImport } from './routes/_authenticated/my-leaves'
import { Route as AuthenticatedMyAttendanceRouteImport } from './routes/_authenticated/my-attendance'
import { Route as AuthenticatedLeavesAdminRouteImport } from './routes/_authenticated/leaves-admin'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCheckInRouteImport } from './routes/_authenticated/check-in'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPinResetsRoute = AuthenticatedPinResetsRouteImport.update({
  id: '/pin-resets',
  path: '/pin-resets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMySalaryRoute = AuthenticatedMySalaryRouteImport.update({
  id: '/my-salary',
  path: '/my-salary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyLeavesRoute = AuthenticatedMyLeavesRouteImport.update({
  id: '/my-leaves',
  path: '/my-leaves',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAttendanceRoute =
  AuthenticatedMyAttendanceRouteImport.update({
    id: '/my-attendance',
    path: '/my-attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeavesAdminRoute =
  AuthenticatedLeavesAdminRouteImport.update({
    id: '/leaves-admin',
    path: '/leaves-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckInRoute = AuthenticatedCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/leaves-admin': typeof AuthenticatedLeavesAdminRoute
  '/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/my-leaves': typeof AuthenticatedMyLeavesRoute
  '/my-salary': typeof AuthenticatedMySalaryRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/pin-resets': typeof AuthenticatedPinResetsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/team': typeof AuthenticatedTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/leaves-admin': typeof AuthenticatedLeavesAdminRoute
  '/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/my-leaves': typeof AuthenticatedMyLeavesRoute
  '/my-salary': typeof AuthenticatedMySalaryRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/pin-resets': typeof AuthenticatedPinResetsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/team': typeof AuthenticatedTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/check-in': typeof AuthenticatedCheckInRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/leaves-admin': typeof AuthenticatedLeavesAdminRoute
  '/_authenticated/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/_authenticated/my-leaves': typeof AuthenticatedMyLeavesRoute
  '/_authenticated/my-salary': typeof AuthenticatedMySalaryRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/pin-resets': typeof AuthenticatedPinResetsRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/check-in'
    | '/clients'
    | '/leaves-admin'
    | '/my-attendance'
    | '/my-leaves'
    | '/my-salary'
    | '/payroll'
    | '/pin-resets'
    | '/plans'
    | '/shifts'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/check-in'
    | '/clients'
    | '/leaves-admin'
    | '/my-attendance'
    | '/my-leaves'
    | '/my-salary'
    | '/payroll'
    | '/pin-resets'
    | '/plans'
    | '/shifts'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/check-in'
    | '/_authenticated/clients'
    | '/_authenticated/leaves-admin'
    | '/_authenticated/my-attendance'
    | '/_authenticated/my-leaves'
    | '/_authenticated/my-salary'
    | '/_authenticated/payroll'
    | '/_authenticated/pin-resets'
    | '/_authenticated/plans'
    | '/_authenticated/shifts'
    | '/_authenticated/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pin-resets': {
      id: '/_authenticated/pin-resets'
      path: '/pin-resets'
      fullPath: '/pin-resets'
      preLoaderRoute: typeof AuthenticatedPinResetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-salary': {
      id: '/_authenticated/my-salary'
      path: '/my-salary'
      fullPath: '/my-salary'
      preLoaderRoute: typeof AuthenticatedMySalaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-leaves': {
      id: '/_authenticated/my-leaves'
      path: '/my-leaves'
      fullPath: '/my-leaves'
      preLoaderRoute: typeof AuthenticatedMyLeavesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-attendance': {
      id: '/_authenticated/my-attendance'
      path: '/my-attendance'
      fullPath: '/my-attendance'
      preLoaderRoute: typeof AuthenticatedMyAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaves-admin': {
      id: '/_authenticated/leaves-admin'
      path: '/leaves-admin'
      fullPath: '/leaves-admin'
      preLoaderRoute: typeof AuthenticatedLeavesAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in': {
      id: '/_authenticated/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthenticatedCheckInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedCheckInRoute: typeof AuthenticatedCheckInRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedLeavesAdminRoute: typeof AuthenticatedLeavesAdminRoute
  AuthenticatedMyAttendanceRoute: typeof AuthenticatedMyAttendanceRoute
  AuthenticatedMyLeavesRoute: typeof AuthenticatedMyLeavesRoute
  AuthenticatedMySalaryRoute: typeof AuthenticatedMySalaryRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPinResetsRoute: typeof AuthenticatedPinResetsRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedCheckInRoute: AuthenticatedCheckInRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedLeavesAdminRoute: AuthenticatedLeavesAdminRoute,
  AuthenticatedMyAttendanceRoute: AuthenticatedMyAttendanceRoute,
  AuthenticatedMyLeavesRoute: AuthenticatedMyLeavesRoute,
  AuthenticatedMySalaryRoute: AuthenticatedMySalaryRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPinResetsRoute: AuthenticatedPinResetsRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
