/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BiometricAttendanceCityRouteImport } from './routes/biometric-attendance.$city'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedRevenueRouteImport } from './routes/_authenticated/revenue'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedPinResetsRouteImport } from './routes/_authenticated/pin-resets'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedMySalaryRouteImport } from './routes/_authenticated/my-salary'
import { Route as AuthenticatedMyLeavesRouteImport } from './routes/_authenticated/my-leaves'
import { Route as AuthenticatedMyAttendanceRouteImport } from './routes/_authenticated/my-attendance'
import { Route as AuthenticatedMarkAttendanceRouteImport } from './routes/_authenticated/mark-attendance'
import { Route as AuthenticatedLiveMapRouteImport } from './routes/_authenticated/live-map'
import { Route as AuthenticatedLeavesAdminRouteImport } from './routes/_authenticated/leaves-admin'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedCheckInRouteImport } from './routes/_authenticated/check-in'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiometricAttendanceCityRoute = BiometricAttendanceCityRouteImport.update({
  id: '/biometric-attendance/$city',
  path: '/biometric-attendance/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevenueRoute = AuthenticatedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPinResetsRoute = AuthenticatedPinResetsRouteImport.update({
  id: '/pin-resets',
  path: '/pin-resets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMySalaryRoute = AuthenticatedMySalaryRouteImport.update({
  id: '/my-salary',
  path: '/my-salary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyLeavesRoute = AuthenticatedMyLeavesRouteImport.update({
  id: '/my-leaves',
  path: '/my-leaves',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAttendanceRoute =
  AuthenticatedMyAttendanceRouteImport.update({
    id: '/my-attendance',
    path: '/my-attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarkAttendanceRoute =
  AuthenticatedMarkAttendanceRouteImport.update({
    id: '/mark-attendance',
    path: '/mark-attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveMapRoute = AuthenticatedLiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeavesAdminRoute =
  AuthenticatedLeavesAdminRouteImport.update({
    id: '/leaves-admin',
    path: '/leaves-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckInRoute = AuthenticatedCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/leaves-admin': typeof AuthenticatedLeavesAdminRoute
  '/live-map': typeof AuthenticatedLiveMapRoute
  '/mark-attendance': typeof AuthenticatedMarkAttendanceRoute
  '/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/my-leaves': typeof AuthenticatedMyLeavesRoute
  '/my-salary': typeof AuthenticatedMySalaryRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/pin-resets': typeof AuthenticatedPinResetsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/biometric-attendance/$city': typeof BiometricAttendanceCityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/leaves-admin': typeof AuthenticatedLeavesAdminRoute
  '/live-map': typeof AuthenticatedLiveMapRoute
  '/mark-attendance': typeof AuthenticatedMarkAttendanceRoute
  '/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/my-leaves': typeof AuthenticatedMyLeavesRoute
  '/my-salary': typeof AuthenticatedMySalaryRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/pin-resets': typeof AuthenticatedPinResetsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/biometric-attendance/$city': typeof BiometricAttendanceCityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/check-in': typeof AuthenticatedCheckInRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/leaves-admin': typeof AuthenticatedLeavesAdminRoute
  '/_authenticated/live-map': typeof AuthenticatedLiveMapRoute
  '/_authenticated/mark-attendance': typeof AuthenticatedMarkAttendanceRoute
  '/_authenticated/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/_authenticated/my-leaves': typeof AuthenticatedMyLeavesRoute
  '/_authenticated/my-salary': typeof AuthenticatedMySalaryRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/pin-resets': typeof AuthenticatedPinResetsRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/revenue': typeof AuthenticatedRevenueRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/biometric-attendance/$city': typeof BiometricAttendanceCityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/app'
    | '/audit'
    | '/branches'
    | '/check-in'
    | '/classes'
    | '/clients'
    | '/leaves-admin'
    | '/live-map'
    | '/mark-attendance'
    | '/my-attendance'
    | '/my-leaves'
    | '/my-salary'
    | '/payroll'
    | '/pin-resets'
    | '/plans'
    | '/revenue'
    | '/shifts'
    | '/team'
    | '/biometric-attendance/$city'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/app'
    | '/audit'
    | '/branches'
    | '/check-in'
    | '/classes'
    | '/clients'
    | '/leaves-admin'
    | '/live-map'
    | '/mark-attendance'
    | '/my-attendance'
    | '/my-leaves'
    | '/my-salary'
    | '/payroll'
    | '/pin-resets'
    | '/plans'
    | '/revenue'
    | '/shifts'
    | '/team'
    | '/biometric-attendance/$city'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/audit'
    | '/_authenticated/branches'
    | '/_authenticated/check-in'
    | '/_authenticated/classes'
    | '/_authenticated/clients'
    | '/_authenticated/leaves-admin'
    | '/_authenticated/live-map'
    | '/_authenticated/mark-attendance'
    | '/_authenticated/my-attendance'
    | '/_authenticated/my-leaves'
    | '/_authenticated/my-salary'
    | '/_authenticated/payroll'
    | '/_authenticated/pin-resets'
    | '/_authenticated/plans'
    | '/_authenticated/revenue'
    | '/_authenticated/shifts'
    | '/_authenticated/team'
    | '/biometric-attendance/$city'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BiometricAttendanceCityRoute: typeof BiometricAttendanceCityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biometric-attendance/$city': {
      id: '/biometric-attendance/$city'
      path: '/biometric-attendance/$city'
      fullPath: '/biometric-attendance/$city'
      preLoaderRoute: typeof BiometricAttendanceCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revenue': {
      id: '/_authenticated/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pin-resets': {
      id: '/_authenticated/pin-resets'
      path: '/pin-resets'
      fullPath: '/pin-resets'
      preLoaderRoute: typeof AuthenticatedPinResetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-salary': {
      id: '/_authenticated/my-salary'
      path: '/my-salary'
      fullPath: '/my-salary'
      preLoaderRoute: typeof AuthenticatedMySalaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-leaves': {
      id: '/_authenticated/my-leaves'
      path: '/my-leaves'
      fullPath: '/my-leaves'
      preLoaderRoute: typeof AuthenticatedMyLeavesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-attendance': {
      id: '/_authenticated/my-attendance'
      path: '/my-attendance'
      fullPath: '/my-attendance'
      preLoaderRoute: typeof AuthenticatedMyAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mark-attendance': {
      id: '/_authenticated/mark-attendance'
      path: '/mark-attendance'
      fullPath: '/mark-attendance'
      preLoaderRoute: typeof AuthenticatedMarkAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-map': {
      id: '/_authenticated/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof AuthenticatedLiveMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaves-admin': {
      id: '/_authenticated/leaves-admin'
      path: '/leaves-admin'
      fullPath: '/leaves-admin'
      preLoaderRoute: typeof AuthenticatedLeavesAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in': {
      id: '/_authenticated/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthenticatedCheckInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCheckInRoute: typeof AuthenticatedCheckInRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedLeavesAdminRoute: typeof AuthenticatedLeavesAdminRoute
  AuthenticatedLiveMapRoute: typeof AuthenticatedLiveMapRoute
  AuthenticatedMarkAttendanceRoute: typeof AuthenticatedMarkAttendanceRoute
  AuthenticatedMyAttendanceRoute: typeof AuthenticatedMyAttendanceRoute
  AuthenticatedMyLeavesRoute: typeof AuthenticatedMyLeavesRoute
  AuthenticatedMySalaryRoute: typeof AuthenticatedMySalaryRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPinResetsRoute: typeof AuthenticatedPinResetsRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedRevenueRoute: typeof AuthenticatedRevenueRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCheckInRoute: AuthenticatedCheckInRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedLeavesAdminRoute: AuthenticatedLeavesAdminRoute,
  AuthenticatedLiveMapRoute: AuthenticatedLiveMapRoute,
  AuthenticatedMarkAttendanceRoute: AuthenticatedMarkAttendanceRoute,
  AuthenticatedMyAttendanceRoute: AuthenticatedMyAttendanceRoute,
  AuthenticatedMyLeavesRoute: AuthenticatedMyLeavesRoute,
  AuthenticatedMySalaryRoute: AuthenticatedMySalaryRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPinResetsRoute: AuthenticatedPinResetsRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedRevenueRoute: AuthenticatedRevenueRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BiometricAttendanceCityRoute: BiometricAttendanceCityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
