-- ============================================================================
-- DAY TIMETABLE: lay out an employee's day hour by hour
--
-- The problem this solves. To have one teacher at the boys' campus for the
-- 09:00 hour and the day campus for the 10:00 hour, an admin currently has to
-- create a separate shift for each campus-and-period, name it, set its times
-- and branch, then go to the staff member and tick the right ones. Rithvika
-- reached twenty-seven shifts that way, with four different spellings of
-- "evening" and a shift called DILEEP. The model was right; the data entry was
-- doing the admin no favours.
--
-- The fix is not a new scheduling model. staff_shifts already supports several
-- legs per person and payroll, check-in, the live map and the late alerts all
-- understand them. What is added is a way to WRITE that structure by describing
-- the day — 09:00-10:00 Boys, 10:00-11:00 Day — and letting the database work
-- out which shifts that implies.
--
-- HOW DUPLICATES ARE PREVENTED, which is the whole point:
--
--   A slot is identified by (tenant, start, end, branch). Ask for the same slot
--   twice and you get the same shift back. Seventeen teachers who all teach the
--   09:00 hour at the boys' campus share ONE shift, not seventeen. A college
--   with 8 periods across 3 campuses tops out at 24 slots however many staff it
--   has, and a partial unique index makes a second identical slot impossible
--   rather than merely unlikely.
--
--   Shifts created this way are flagged is_timetable_slot and named
--   deterministically ("09:00-10:00 · BOYS CAMPUS"). Hand-made shifts are left
--   completely alone — the uniqueness rule applies only to generated slots, so
--   an employer who wants two differently-configured 9 AM shifts still can.
-- ============================================================================

ALTER TABLE public.shifts
  ADD COLUMN IF NOT EXISTS is_timetable_slot BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN public.shifts.is_timetable_slot IS
  'Generated by the day-timetable builder. Deduplicated on (tenant, start, end, branch).';

-- Only generated slots are deduplicated. Hand-made shifts keep their freedom.
-- COALESCE on branch_id because NULL is not equal to NULL in a unique index,
-- which would let unlimited branch-less slots pile up.
CREATE UNIQUE INDEX IF NOT EXISTS uq_timetable_slot
  ON public.shifts (tenant_id, start_time, end_time, COALESCE(branch_id, '00000000-0000-0000-0000-000000000000'::uuid))
  WHERE is_timetable_slot;

-- ── Replace a staff member's whole day in one call ──────────────────────────
-- _slots is [{"start":"09:00","end":"10:00","branch_id":"…"|null}, …]
CREATE OR REPLACE FUNCTION public.set_staff_timetable(
  _tenant_id UUID,
  _user_id   UUID,
  _slots     JSONB
)
RETURNS TABLE (slots_applied INT, shifts_created INT, shifts_reused INT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  r          RECORD;
  v_shift    UUID;
  v_created  INT := 0;
  v_reused   INT := 0;
  v_applied  INT := 0;
  v_ids      UUID[] := '{}';
  v_label    TEXT;
BEGIN
  -- SECURITY DEFINER, so authorisation is explicit. Super admins are included
  -- deliberately: managing a customer's setup is the job.
  IF NOT (public.is_tenant_admin(auth.uid(), _tenant_id) OR public.is_super_admin(auth.uid())) THEN
    RAISE EXCEPTION 'Not authorised to edit this company''s timetable'
      USING ERRCODE = '42501';
  END IF;

  -- The staff member must belong to this company. Without this an admin could
  -- rewrite a stranger's day by passing someone else's id.
  IF NOT EXISTS (SELECT 1 FROM public.profiles p
                  WHERE p.id = _user_id AND p.tenant_id = _tenant_id) THEN
    RAISE EXCEPTION 'That staff member is not in this company' USING ERRCODE = '42501';
  END IF;

  FOR r IN
    SELECT (s->>'start')::TIME AS st,
           (s->>'end')::TIME   AS en,
           NULLIF(s->>'branch_id', '')::UUID AS br
    FROM jsonb_array_elements(COALESCE(_slots, '[]'::jsonb)) s
  LOOP
    IF r.st IS NULL OR r.en IS NULL THEN
      RAISE EXCEPTION 'Every slot needs a start and end time';
    END IF;
    -- An overnight slot is legitimate (21:00-06:00); a zero-length one is not.
    IF r.st = r.en THEN
      RAISE EXCEPTION 'A slot cannot start and end at the same time (%)', r.st;
    END IF;
    IF r.br IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.branches b WHERE b.id = r.br AND b.tenant_id = _tenant_id
    ) THEN
      RAISE EXCEPTION 'That branch does not belong to this company';
    END IF;

    v_label := to_char(r.st, 'HH24:MI') || '-' || to_char(r.en, 'HH24:MI')
               || COALESCE(' · ' || (SELECT b.name FROM public.branches b WHERE b.id = r.br), '');

    -- Find the slot, or make it. The unique index is what guarantees the
    -- "find" half actually finds rather than racing another admin.
    SELECT id INTO v_shift
    FROM public.shifts
    WHERE tenant_id = _tenant_id AND is_timetable_slot
      AND start_time = r.st AND end_time = r.en
      AND branch_id IS NOT DISTINCT FROM r.br;

    IF v_shift IS NULL THEN
      INSERT INTO public.shifts
        (tenant_id, name, start_time, end_time, branch_id, break_minutes,
         grace_minutes, is_active, is_timetable_slot)
      VALUES (_tenant_id, v_label, r.st, r.en, r.br, 0, 10, true, true)
      ON CONFLICT DO NOTHING
      RETURNING id INTO v_shift;

      IF v_shift IS NULL THEN
        -- Someone created the same slot between our SELECT and INSERT.
        SELECT id INTO v_shift FROM public.shifts
        WHERE tenant_id = _tenant_id AND is_timetable_slot
          AND start_time = r.st AND end_time = r.en
          AND branch_id IS NOT DISTINCT FROM r.br;
        v_reused := v_reused + 1;
      ELSE
        v_created := v_created + 1;
      END IF;
    ELSE
      -- Reactivate a slot that was archived earlier and is wanted again.
      UPDATE public.shifts SET is_active = true WHERE id = v_shift AND NOT is_active;
      v_reused := v_reused + 1;
    END IF;

    v_ids := v_ids || v_shift;
    v_applied := v_applied + 1;
  END LOOP;

  -- Replace this person's generated legs wholesale, so removing a slot from
  -- the timetable actually removes it. Hand-assigned shifts are untouched:
  -- only rows pointing at generated slots are cleared.
  DELETE FROM public.staff_shifts ss
   USING public.shifts s
   WHERE ss.user_id = _user_id
     AND ss.tenant_id = _tenant_id
     AND s.id = ss.shift_id
     AND s.is_timetable_slot;

  IF array_length(v_ids, 1) > 0 THEN
    INSERT INTO public.staff_shifts (tenant_id, user_id, shift_id)
    SELECT _tenant_id, _user_id, unnest
    FROM unnest(v_ids)
    ON CONFLICT DO NOTHING;
  END IF;

  RETURN QUERY SELECT v_applied, v_created, v_reused;
END;
$$;

REVOKE ALL ON FUNCTION public.set_staff_timetable(UUID, UUID, JSONB) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_staff_timetable(UUID, UUID, JSONB) TO authenticated, service_role;

-- ── Read one person's day back ──────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.staff_timetable(_tenant_id UUID, _user_id UUID)
RETURNS TABLE (shift_id UUID, start_time TIME, end_time TIME,
               branch_id UUID, branch_name TEXT, generated BOOLEAN)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT (public.is_tenant_admin(auth.uid(), _tenant_id)
          OR public.is_super_admin(auth.uid())
          OR auth.uid() = _user_id) THEN
    RAISE EXCEPTION 'Not authorised' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT s.id, s.start_time, s.end_time, s.branch_id, b.name, s.is_timetable_slot
  FROM public.staff_shifts ss
  JOIN public.shifts s   ON s.id = ss.shift_id AND s.is_active
  LEFT JOIN public.branches b ON b.id = s.branch_id
  WHERE ss.user_id = _user_id AND ss.tenant_id = _tenant_id
  ORDER BY s.start_time;
END;
$$;

REVOKE ALL ON FUNCTION public.staff_timetable(UUID, UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.staff_timetable(UUID, UUID) TO authenticated, service_role;

NOTIFY pgrst, 'reload schema';
