// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL =
      process.env.SUPABASE_URL
      || process.env.VITE_SUPABASE_URL
      || "https://excqnzlfjiddvyyjtxpo.supabase.co";
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY
      || process.env.VITE_SUPABASE_PUBLISHABLE_KEY
      || "";

    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Missing or malformed Authorization header');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    // Use service_role for token verification — it works regardless of which
    // publishable key the browser was issued the token with. getUser(token)
    // hits Supabase's /auth/v1/user endpoint which validates the JWT server-side.
    const verifyKey = process.env.SUPABASE_SERVICE_ROLE_KEY || SUPABASE_PUBLISHABLE_KEY;
    if (!verifyKey) {
      throw new Error('Server config error: no Supabase key available to verify tokens');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL,
      verifyKey,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data: userData, error: userErr } = await supabase.auth.getUser(token);
    if (userErr || !userData?.user) {
      console.error('[auth-middleware] getUser failed:', userErr);
      throw new Error(`Unauthorized: ${userErr?.message || 'Invalid token'}`);
    }

    return next({
      context: {
        supabase,
        userId: userData.user.id,
        claims: userData.user,
      },
    });
  },
);
